ToDoApp/Models/ErrorViewModel.cs
using System;

namespace ToDoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApp/Models/ToDoGoal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models
{
    public class ToDoGoal
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [Display(Name = "Due date")]
        public DateTime? DueDate { get; set; }
        public string Notes { get; set; }
        [Display(Name = "Need to remind")]
        public bool NeedToRemind { get; set; }
        [Display(Name = "Done")]
        public bool IsDone { get; set; } = false;
        [Display(Name = "To archive")]
        public bool IsArchived { get; set; } = false;
    }
}

ToDoApp/Models/ToDoTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models
{
    public class ToDoTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [Display(Name = "Done")]
        public bool IsDone { get; set; } = false;
        [Display(Name = "To archive")]
        public bool IsArchived { get; set; } = false;
    }
}

ToDoApp/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoApp.Core.Models;
using ToDoApp.DAL;
using ToDoApp.Core;
using ToDoApp.Core.Services;

namespace ToDoApp.Controllers
{
    public class GoalController : Controller
    {
        private GoalsService _goalsService;

        public GoalController(GoalsService goalsService)
        {
            _goalsService = goalsService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _goalsService.GetAllGoals());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ToDoGoal goal)
        {
            try
            {
                await _goalsService.AddGoal(goal);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            ToDoGoal goal = await _goalsService.GetGoal(id);
            if (goal != null)
                return View(goal);
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ToDoGoal goal)
        {
            try
            {
                await _goalsService.UpdateGoal(goal);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var ret = await _goalsService.Delete(id);
            return Json(ret);
        }

        [HttpPost]
        public async Task<IActionResult> ToggleDone(int id)
        {
            var ret = await _goalsService.ToggleDone(id);
            return Json(ret);
        }
    }
}

ToDoApp/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoApp.Core;
using ToDoApp.Core.Models;
using ToDoApp.Core.Services;
using ToDoApp.DAL;
using ToDoApp.DAL.Data;

namespace ToDoApp.Controllers
{
    public class TaskController : Controller
    {
        private TasksService _tasksService;

        public TaskController(TasksService tasksService)
        {
            _tasksService = tasksService;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Goals"] = await _tasksService.GetActualGoals();
            return View(await _tasksService.GetNonArchivedTasks());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ToDoTask task)
        {
            try
            {
                await _tasksService.AddTask(task);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ToDoTask task)
        {
            try
            {
                await _tasksService.UpdateTask(task);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var task = await _tasksService.GetTask(id);
            if (task != null)
                return View(task);
            return NotFound();
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var task = await _tasksService.GetTask(id);
            if (task != null)
                return View(task);
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var ret = await _tasksService.Delete(id);
            return Json(ret);
        }

        [HttpPost]
        public async Task<IActionResult> ToggleDone(int id)
        {
            var ret = await _tasksService.ToggleDone(id);
            return Json(ret);
        }

        public IActionResult DeleteDoneTasks()
        {
            _tasksService.DeleteDoneTasks();
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoApp/Views/Goal/Create.cshtml
@model ToDoGoal

@{
    ViewData["Title"] = "Create";
}

<h1>Create Goal</h1>


<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input type="date" class="form-control" id="DueDate" name="DueDate"/>
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                
                <textarea class="form-control" id="Notes" name="Notes"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NeedToRemind" /> @Html.DisplayNameFor(model => model.NeedToRemind)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDone" /> @Html.DisplayNameFor(model => model.IsDone)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsArchived" /> @Html.DisplayNameFor(model => model.IsArchived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApp/Views/Goal/Edit.cshtml
@model ToDoGoal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" type="date" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <textarea asp-for="Notes" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NeedToRemind" /> @Html.DisplayNameFor(model => model.NeedToRemind)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDone" /> @Html.DisplayNameFor(model => model.IsDone)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsArchived" /> @Html.DisplayNameFor(model => model.IsArchived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApp/Views/Goal/Index.cshtml
@model IEnumerable<ToDoGoal>

@{
    ViewData["Title"] = "Goals";
}

<h1>Goals</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">New goal</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var trClass = (item.IsDone ? " done" : "");
            
            <tr data-id="@item.Id" class="@trClass">
                <td>
                    <div class="goal-item">
                        @Html.DisplayFor(modelItem => item.Title)
                    </div>
                </td>
                <td>
                    @{
                        var date = string.Empty;
                        if (item.DueDate != null)
                        {
                            date = ((DateTime)item.DueDate).ToShortDateString();
                        }
                    }
                    @date
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id"><i class="icon-normal fas fa-edit"></i></a>
                    <i class="icon-normal delete deleteGoal fas fa-trash"></i>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    var UrlSettings = {
        ToggleDoneGoalUrl: '@Url.Action("ToggleDone", "Goal")',
        DeleteGoalUrl : '@Url.Action("Delete", "Goal")'
        }
</script>

ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/28a544b9ce.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Task" asp-action="Index">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Goal" asp-action="Index">Goals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoApp/Views/Task/AddItem.cshtml
@model ToDoTask

<form asp-action="Create" method="POST">
    <div class="row">
        <div class="col-6">
            <input asp-for="Title" placeholder="New Item" class="form-control">
        </div>
        <div class="col-4">
            <button type="submit" class="btn btn-outline-secondary">Add</button>
        </div>
    </div>
</form>

ToDoApp/Views/Task/Delete.cshtml
@model ToDoTask

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsArchived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsArchived)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ToDoApp/Views/Task/Details.cshtml
@model ToDoTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDoTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsArchived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsArchived)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ToDoApp/Views/Task/Edit.cshtml
@model ToDoTask

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDone" /> @Html.DisplayNameFor(model => model.IsDone)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsArchived" /> @Html.DisplayNameFor(model => model.IsArchived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoApp/Views/Task/Index.cshtml
@model IEnumerable<ToDoTask>

@{
    ViewData["Title"] = "Tasks";
    List<ToDoGoal> goals = (List<ToDoGoal>)ViewData["Goals"];
}

<h1>Your tasks</h1>


<table class="table">
    <thead>
            <tr>
                <th>
                </th>
                <th>
                    <i class="icon-normal delete fas fa-trash-alt" onclick="deleteDoneTasks()"></i>
                </th>
            </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.Id">
                <td >
                    @{ 
                        var itemClass = "task-item" + (item.IsDone ? " done" : "");
                    }
                    <div class="@itemClass">                        
                        @Html.DisplayFor(modelItem => item.Title)
                    </div>
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id"><i class="icon-normal fas fa-edit"></i></a>
                    
                    <i class="icon-normal delete deleteTask fas fa-trash"></i>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="panel-footer add-item-form">
    @await Html.PartialAsync("AddItem", new ToDoTask())
</div>

<h1 style="margin-top:5%">Your goals</h1>
<table class="table" >    
    <tbody>
        @foreach (var item in goals)
        {
            <tr>
                <td>
                    @item.Title
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    var UrlSettings = {
        ToggleDoneTaskUrl: '@Url.Action("ToggleDone", "Task")',
        DeleteTaskUrl: '@Url.Action("Delete", "Task")',
        DeleteDoneTasksUrl : '@Url.Action("DeleteDoneTasks", "Task")'
        }
</script>